stages:
  - test
  - build
  - deploy

variables:
  GO_PROJECT_PATH: $CI_PROJECT_DIR

before_script:
  - export GO111MODULE=on
  - cd $GO_PROJECT_PATH

test:
  stage: test
  script:
    - go test ./handler/...

build:
  stage: build
  script:
    - go build -o myapp
  artifacts:
    paths:
      - myapp

deploy:
  stage: deploy
  script:
    - echo "Deploying the application"
    # Add your deployment scripts here. This could be SSH commands, Kubernetes deployments, etc.
