version: '3.8' # Use a specific version supported by your Docker version

services:
  golangcicdpipeline:
    container_name: golangcicdpipeline
    image: registry.gitlab.com/bxbzwe/golangcicdpipeline:${TAG-latest}
    env_file: .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - golangcicdpipeline
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
